### ISSUE TITLE
Pinterest Share Button Issue

### ISSUE THREAD

**Issue by joshua-isaac** [nygardk/react-share#344]
Hello all, i have a Twitter, Facebook & Pinterest Share button. The Twitter and Facebook buttons work fine, however when i click on the Pinterest Share button i get this error in console: 

`
Uncaught (in promise) AssertionError: pinterest.url
    at new AssertionError (http://localhost:8000/commons.js:91979:28)
    at assert (http://localhost:8000/commons.js:91987:15)
    at pinterestLink (http://localhost:8000/commons.js:90629:66)
    at ShareButton.<anonymous> (http://localhost:8000/commons.js:90962:32)
    at step (http://localhost:8000/commons.js:90892:23)
    at Object.next (http://localhost:8000/commons.js:90873:53)
    at http://localhost:8000/commons.js:90867:71
    at new Promise (<anonymous>)
    at ./node_modules/react-share/es/ShareButton.js.__awaiter (http://localhost:8000/commons.js:90863:12)
    at ShareButton._this.handleClick (http://localhost:8000/commons.js:90956:55)
    at HTMLUnknownElement.callCallback (http://localhost:8000/commons.js:37087:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8000/commons.js:37136:16)
    at invokeGuardedCallback (http://localhost:8000/commons.js:37191:31)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:8000/commons.js:37205:25)
    at executeDispatch (http://localhost:8000/commons.js:37288:3)
    at executeDispatchesInOrder (http://localhost:8000/commons.js:37313:5)
    at executeDispatchesAndRelease (http://localhost:8000/commons.js:40177:5)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8000/commons.js:40186:10)
    at forEachAccumulated (http://localhost:8000/commons.js:40158:8)
    at runEventsInBatch (http://localhost:8000/commons.js:40203:3)
    at runExtractedPluginEventsInBatch (http://localhost:8000/commons.js:40413:3)
    at handleTopLevel (http://localhost:8000/commons.js:40457:5)
    at batchedEventUpdates$1 (http://localhost:8000/commons.js:58770:12)
    at batchedEventUpdates (http://localhost:8000/commons.js:37694:12)
    at dispatchEventForLegacyPluginEventSystem (http://localhost:8000/commons.js:40467:5)
    at attemptToDispatchEvent (http://localhost:8000/commons.js:41166:5)
    at dispatchEvent (http://localhost:8000/commons.js:41088:19)
    at unstable_runWithPriority (http://localhost:8000/commons.js:63045:12)
    at runWithPriority$1 (http://localhost:8000/commons.js:47938:10)
    at discreteUpdates$1 (http://localhost:8000/commons.js:58786:12)
    at discreteUpdates (http://localhost:8000/commons.js:37705:12)
    at dispatchDiscreteEvent (http://localhost:8000/commons.js:41067:3)
`

This is how my Pinterest Share Button is set up:

`
       <PinterestShareButton
                  media="https://images.unsplash.com/photo-1482066490729-6f26115b60dc?ixlib=rb-1.2.1&w=1000&q=80"
                  description={post.title}
                >
                  <PinterestIcon size="2.5rem" />
                </PinterestShareButton>
`
Any idea on what I'm doing wrong?

**Comment by joshua-isaac** [comment]
Looks like the `<Pinterst />` requires a `media` AND `url` property.
